apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coifesp
resources:
  - namespace.yaml
  - configmaps.yaml
  - serviceaccounts-rbac.yaml
  - control-plane.yaml
  - agent-worker.yaml
  - tool-worker.yaml
  - disruption-budgets.yaml
  - network-policies.yaml
  - control-plane-hpa.yaml

