#!/bin/sh
set -eu

: "${TEAMCOOP_DB_PASSWORD:?TEAMCOOP_DB_PASSWORD is required}"
: "${KEYCLOAK_DB_PASSWORD:?KEYCLOAK_DB_PASSWORD is required}"

psql --set ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE ROLE team_cooperation_app LOGIN PASSWORD '${TEAMCOOP_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE team_cooperation_keycloak LOGIN PASSWORD '${KEYCLOAK_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE DATABASE team_cooperation OWNER team_cooperation_app;
CREATE DATABASE team_cooperation_keycloak OWNER team_cooperation_keycloak;
SQL
