"""Project planning drafts generated by Agent turns.

An Agent produces a structured plan (``coifesp.project-plan.v1``); the plan
is stored as a reviewable draft with team requirement recommendations. Nothing
is projected into business objects until the project owner confirms.
"""

from __future__ import annotations

import hashlib
import json
import secrets
from datetime import UTC, datetime

from sqlalchemy import and_, select
from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError

from ..errors import GovernanceConflictError, ResourceNotFound
from ..work_graph import ProjectWorkGraphService, WorkNodeType
from .models import (
    PlanDraftStatus,
    ProjectPlanDraft,
    ProjectTeamRequirementDraft,
)
from .repository import (
    PROJECT_PLAN_DRAFTS,
    PROJECTS,
    PROJECT_TEAM_REQUIREMENT_DRAFTS,
    PROJECT_TEAMS,
)
from .service import ProductAccountService, TeamCollaborationService
from .plan_schema import PLAN_V2, parse_project_plan

_TEAM_CATEGORIES = frozenset(
    {"product", "engineering", "quality", "design", "operations", "custom"}
)


def _is_duplicate_key_error(exc: IntegrityError) -> bool:
    """Only a primary/unique-key conflict counts as an idempotent replay.

    Foreign-key failures, NOT NULL or check-constraint violations must abort
    the approval instead of being silently swallowed.
    """
    message = str(getattr(exc, "orig", exc)).lower()
    return "unique" in message or "duplicate" in message


def _plan_sha256(payload: dict) -> str:
    canonical = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


class ProjectPlanningService:
    def __init__(
        self,
        engine: Engine,
        *,
        collaboration: TeamCollaborationService | None = None,
        work_graph: ProjectWorkGraphService | None = None,
    ) -> None:
        self.engine = engine
        self.collaboration = collaboration
        self.work_graph = work_graph

    def import_plan_draft(
        self,
        *,
        project_id: str,
        actor_id: str,
        content: str,
        source_conversation_id: str | None = None,
        source_turn_id: str | None = None,
        source_run_id: str | None = None,
    ) -> ProjectPlanDraft:
        """Parse an Agent plan output into a reviewable plan draft."""
        self._require_participant(project_id=project_id, actor_id=actor_id)
        if source_run_id:
            # Terminal projection is retried until the turn is completed; a
            # single run must only ever produce one draft.
            with self.engine.connect() as connection:
                existing = connection.execute(
                    select(PROJECT_PLAN_DRAFTS.c.draft_id).where(
                        and_(
                            PROJECT_PLAN_DRAFTS.c.project_id == project_id,
                            PROJECT_PLAN_DRAFTS.c.source_run_id == source_run_id,
                        )
                    )
                ).scalar_one_or_none()
            if existing is not None:
                return self._plan_row_with_engine(draft_id=existing)
        parsed = parse_project_plan(content)
        goals, scope = parsed.goals, parsed.scope
        phases, milestones = parsed.phases, parsed.milestones
        risks, dependencies = parsed.risks, parsed.dependencies
        criteria = parsed.acceptance_criteria
        normalized_requirements = parsed.team_requirements
        draft_payload = parsed.payload
        now = datetime.now(UTC)
        try:
            with self.engine.begin() as connection:
                draft_id = f"plan-{secrets.token_hex(12)}"
                connection.execute(
                    PROJECT_PLAN_DRAFTS.insert().values(
                        draft_id=draft_id,
                        project_id=project_id,
                        source_conversation_id=source_conversation_id,
                        source_turn_id=source_turn_id,
                        source_run_id=source_run_id,
                        schema_version=parsed.schema_version,
                        plan_payload=draft_payload,
                        goals=goals,
                        scope=scope,
                        phases=json.dumps(phases, ensure_ascii=False),
                        milestones=json.dumps(milestones, ensure_ascii=False),
                        risks=json.dumps(risks, ensure_ascii=False),
                        dependencies=json.dumps(dependencies, ensure_ascii=False),
                        acceptance_criteria=json.dumps(criteria, ensure_ascii=False),
                        content_sha256=_plan_sha256(draft_payload),
                        status=PlanDraftStatus.DRAFTING.value,
                        version=1,
                        created_by=actor_id,
                        created_at=now,
                        updated_at=now,
                        approved_at=None,
                        rejection_reason="",
                    )
                )
                for entry in normalized_requirements:
                    connection.execute(
                        PROJECT_TEAM_REQUIREMENT_DRAFTS.insert().values(
                            requirement_id=f"req-{secrets.token_hex(12)}",
                            project_id=project_id,
                            plan_draft_id=draft_id,
                            team_category=entry["team_category"],
                            team_count=entry["count"],
                            rationale=entry["rationale"],
                            status=PlanDraftStatus.DRAFTING.value,
                            created_by=actor_id,
                            created_at=now,
                            approved_at=None,
                        )
                    )
                return self._plan_row(connection, draft_id=draft_id)
        except IntegrityError:
            # The unique source_run_id constraint guarantees a concurrent
            # projection retry converges on the already imported draft.
            if source_run_id:
                existing = self._find_draft_by_run(source_run_id)
                if existing is not None:
                    return self._plan_row_with_engine(draft_id=existing)
            raise

    def list_plan_drafts(self, *, project_id: str, actor_id: str) -> tuple[ProjectPlanDraft, ...]:
        self._require_participant(project_id=project_id, actor_id=actor_id)
        with self.engine.connect() as connection:
            rows = (
                connection.execute(
                    select(PROJECT_PLAN_DRAFTS)
                    .where(PROJECT_PLAN_DRAFTS.c.project_id == project_id)
                    .order_by(PROJECT_PLAN_DRAFTS.c.created_at.desc())
                )
                .mappings()
                .all()
            )
        return tuple(self._plan(row) for row in rows)

    def list_team_requirements(
        self, *, project_id: str, actor_id: str
    ) -> tuple[ProjectTeamRequirementDraft, ...]:
        self._require_participant(project_id=project_id, actor_id=actor_id)
        with self.engine.connect() as connection:
            rows = (
                connection.execute(
                    select(PROJECT_TEAM_REQUIREMENT_DRAFTS)
                    .where(PROJECT_TEAM_REQUIREMENT_DRAFTS.c.project_id == project_id)
                    .order_by(PROJECT_TEAM_REQUIREMENT_DRAFTS.c.created_at)
                )
                .mappings()
                .all()
            )
        return tuple(self._requirement(row) for row in rows)

    def approve_plan_draft(
        self, *, project_id: str, draft_id: str, actor_id: str
    ) -> ProjectPlanDraft:
        """Confirm the plan and project it into project business objects.

        Business projection runs before the draft is marked approved and every
        projected object gets a deterministic id derived from the draft id, so
        a crash between projection steps leaves the draft open (DRAFTING) for
        a safe retry and a retry never duplicates topics or tasks. The draft
        is finalized last with a conditional update so concurrent approvals
        cannot double-confirm.
        """
        with self.engine.connect() as connection:
            draft = self._plan_row(connection, draft_id=draft_id)
            if draft.project_id != project_id:
                raise ResourceNotFound("plan draft is unavailable")
            actor = ProductAccountService._account_row(connection, actor_id)
            owner_team = connection.execute(
                select(PROJECTS.c.owner_team_id).where(PROJECTS.c.project_id == project_id)
            ).scalar_one_or_none()
            if owner_team is None:
                raise ResourceNotFound("project is unavailable")
            if actor["team_id"] != owner_team:
                raise GovernanceConflictError(
                    "only the initiating team may confirm the project plan"
                )
            if draft.status is not PlanDraftStatus.DRAFTING:
                raise GovernanceConflictError("plan draft is no longer open")
        # Project business objects first; each create is idempotent.
        self._project_plan_topic(project_id=project_id, draft=draft, actor_id=actor_id)
        self._materialize_plan(project_id=project_id, draft=draft, actor_id=actor_id)
        self._materialize_work_graph(project_id=project_id, draft=draft, actor_id=actor_id)
        now = datetime.now(UTC)
        with self.engine.begin() as connection:
            updated = connection.execute(
                PROJECT_PLAN_DRAFTS.update()
                .where(
                    and_(
                        PROJECT_PLAN_DRAFTS.c.draft_id == draft_id,
                        PROJECT_PLAN_DRAFTS.c.status == PlanDraftStatus.DRAFTING.value,
                    )
                )
                .values(status=PlanDraftStatus.APPROVED.value, approved_at=now, updated_at=now)
            )
            if updated.rowcount == 0:
                raise GovernanceConflictError("plan draft is no longer open")
            connection.execute(
                PROJECT_TEAM_REQUIREMENT_DRAFTS.update()
                .where(
                    and_(
                        PROJECT_TEAM_REQUIREMENT_DRAFTS.c.plan_draft_id == draft_id,
                        PROJECT_TEAM_REQUIREMENT_DRAFTS.c.status == PlanDraftStatus.DRAFTING.value,
                    )
                )
                .values(status=PlanDraftStatus.APPROVED.value, approved_at=now)
            )
        return self._plan_row_with_engine(draft_id=draft_id)

    def reject_plan_draft(
        self, *, project_id: str, draft_id: str, actor_id: str, reason: str
    ) -> ProjectPlanDraft:
        now = datetime.now(UTC)
        with self.engine.begin() as connection:
            draft = self._plan_row(connection, draft_id=draft_id)
            if draft.project_id != project_id:
                raise ResourceNotFound("plan draft is unavailable")
            self._require_participant(project_id=project_id, actor_id=actor_id)
            if draft.status is not PlanDraftStatus.DRAFTING:
                raise GovernanceConflictError("plan draft is no longer open")
            connection.execute(
                PROJECT_PLAN_DRAFTS.update()
                .where(PROJECT_PLAN_DRAFTS.c.draft_id == draft_id)
                .values(
                    status=PlanDraftStatus.REJECTED.value,
                    rejection_reason=(reason or "").strip(),
                    updated_at=now,
                )
            )
            return self._plan_row(connection, draft_id=draft_id)

    def _project_plan_topic(self, *, project_id, draft, actor_id) -> None:
        if self.collaboration is None:
            return
        summary = f"项目计划已确认：{draft.goals[:200]}" + (
            f"（阶段 {len(draft.phases)} 个，风险 {len(draft.risks)} 项）"
            if draft.phases or draft.risks
            else ""
        )
        try:
            self.collaboration.create_topic(
                topic_id=f"plan-confirm-{draft.draft_id}",
                project_id=project_id,
                actor_id=actor_id,
                title="项目计划确认",
                context=summary,
                source_agent_run_id=draft.source_run_id,
            )
        except IntegrityError as exc:
            if not _is_duplicate_key_error(exc):
                raise
            # A previous partial projection already created this topic.
            pass

    def _materialize_plan(self, *, project_id, draft, actor_id) -> None:
        """Project the confirmed plan into actionable business objects.

        Milestones become project topics, phases become tasks sent to the
        participating team matching the phase's team_category, and team
        requirement recommendations stay visible as approved requirement
        drafts the owner can follow up on. Every object uses a deterministic
        id derived from the draft id so an approve retry after a crash never
        duplicates anything. A phase without an assignable team (missing
        team_category or a team with that kind not yet in the project) is
        recorded as an open topic instead of being silently dropped.
        """
        collaboration = self.collaboration
        if collaboration is None:
            return
        if draft.schema_version == PLAN_V2:
            self._materialize_v2_tasks(project_id=project_id, draft=draft, actor_id=actor_id)
            return
        teams_by_kind = self._project_teams_by_kind(project_id)
        owner_team = self._project_owner_team(project_id)
        for index, milestone in enumerate(draft.milestones):
            name = str(milestone.get("name") or "未命名里程碑").strip()
            target = str(milestone.get("target") or "").strip()
            if not name:
                continue
            try:
                collaboration.create_topic(
                    topic_id=f"plan-ms-{draft.draft_id}-{index}",
                    project_id=project_id,
                    actor_id=actor_id,
                    title=f"里程碑：{name}",
                    context=f"目标时间：{target}" if target else name,
                    source_agent_run_id=draft.source_run_id,
                )
            except IntegrityError as exc:
                # Already projected by a retry; only duplicate ids are
                # idempotent successes, anything else aborts the approval.
                if not _is_duplicate_key_error(exc):
                    raise
                continue
        for index, phase in enumerate(draft.phases):
            name = str(phase.get("name") or "").strip()
            if not name:
                continue
            description = str(phase.get("description") or "").strip()
            team_category = str(phase.get("team_category") or "").strip()
            target_team = teams_by_kind.get(team_category) if team_category else None
            if target_team is None or target_team == owner_team:
                # No cross-team task is possible: surface the phase as an open
                # proposal the owner team can still act on.
                try:
                    collaboration.create_topic(
                        topic_id=f"plan-ph-{draft.draft_id}-{index}",
                        project_id=project_id,
                        actor_id=actor_id,
                        title=f"阶段建议：{name}",
                        context=description or name,
                        source_agent_run_id=draft.source_run_id,
                    )
                except IntegrityError as exc:
                    if not _is_duplicate_key_error(exc):
                        raise
                    continue
                continue
            criteria = (
                draft.acceptance_criteria[0]
                if draft.acceptance_criteria
                else "按项目计划验收标准执行"
            )
            try:
                collaboration.create_task(
                    task_id=f"plan-ph-{draft.draft_id}-{index}",
                    project_id=project_id,
                    actor_id=actor_id,
                    target_team_id=target_team,
                    title=f"阶段执行：{name}",
                    description=description or name,
                    acceptance_criteria=criteria,
                )
            except IntegrityError as exc:
                if not _is_duplicate_key_error(exc):
                    raise
                continue

    def _materialize_v2_tasks(self, *, project_id, draft, actor_id) -> None:
        collaboration = self.collaboration
        if collaboration is None:
            return
        teams_by_kind = self._project_teams_by_kind(project_id)
        owner_team = self._project_owner_team(project_id)
        for task in draft.plan_payload.get("tasks", ()):
            local_id = task["id"]
            target_team = teams_by_kind.get(task["team_category"])
            if target_team is None or target_team == owner_team:
                raise GovernanceConflictError(
                    f"plan task {local_id} has no assignable participating team"
                )
            criteria = task.get("acceptance_criteria") or draft.acceptance_criteria
            criterion = criteria[0] if criteria else "按项目计划验收标准执行"
            try:
                collaboration.create_task(
                    task_id=self._stable_id("plan-task", draft.draft_id, local_id),
                    project_id=project_id,
                    actor_id=actor_id,
                    target_team_id=target_team,
                    title=task["title"],
                    description=task["description"],
                    acceptance_criteria=criterion,
                )
            except IntegrityError as exc:
                if not _is_duplicate_key_error(exc):
                    raise

    def _materialize_work_graph(self, *, project_id, draft, actor_id) -> None:
        graph = self.work_graph
        if graph is None:
            return
        if draft.schema_version == PLAN_V2:
            self._materialize_v2_work_graph(project_id=project_id, draft=draft, actor_id=actor_id)
            return
        self._materialize_v1_work_graph(project_id=project_id, draft=draft, actor_id=actor_id)

    def _materialize_v2_work_graph(self, *, project_id, draft, actor_id) -> None:
        graph = self.work_graph
        payload = draft.plan_payload
        local_nodes: dict[str, str] = {}
        goal = payload["goal"]
        goal_id = self._stable_id("goal", draft.draft_id, goal["id"])
        _, goal_node = graph.create_goal(
            goal_id=goal_id,
            project_id=project_id,
            title=goal["title"],
            description=goal["description"],
            success_criteria=tuple(goal["success_criteria"]),
            created_by=actor_id,
        )
        local_nodes[goal["id"]] = goal_node.node_id

        for item in payload.get("requirements", ()):
            requirement_id = self._stable_id("requirement", draft.draft_id, item["id"])
            _, node = graph.create_requirement(
                requirement_id=requirement_id,
                project_id=project_id,
                goal_id=self._stable_id("goal", draft.draft_id, item["goal_id"]),
                title=item["title"],
                description=item["description"],
                requirement_type=item["requirement_type"],
                priority=item["priority"],
                source_type="plan",
                source_id=draft.draft_id,
            )
            local_nodes[item["id"]] = node.node_id

        for item in payload.get("milestones", ()):
            milestone_id = self._stable_id("milestone", draft.draft_id, item["id"])
            _, node = graph.create_milestone(
                milestone_id=milestone_id,
                project_id=project_id,
                title=item["title"],
                description=item["description"],
                target_at=self._optional_datetime(item.get("target_at")),
                completion_policy=item["completion_policy"],
            )
            local_nodes[item["id"]] = node.node_id

        teams_by_kind = self._project_teams_by_kind(project_id)
        for item in payload.get("phases", ()):
            milestone_id = (
                self._stable_id("milestone", draft.draft_id, item["milestone_id"])
                if item.get("milestone_id")
                else None
            )
            owner_team_id = (
                teams_by_kind.get(item["team_category"]) if item.get("team_category") else None
            )
            _, node = graph.create_phase(
                phase_id=self._stable_id("phase", draft.draft_id, item["id"]),
                project_id=project_id,
                title=item["title"],
                description=item["description"],
                milestone_id=milestone_id,
                owner_team_id=owner_team_id,
            )
            local_nodes[item["id"]] = node.node_id

        for item in payload.get("risks", ()):
            _, node = graph.create_risk(
                risk_id=self._stable_id("risk", draft.draft_id, item["id"]),
                project_id=project_id,
                title=item["title"],
                description=item["description"],
                severity=item["severity"],
                likelihood=item["likelihood"],
                mitigation=item["mitigation"],
                source_run_id=draft.source_run_id,
            )
            local_nodes[item["id"]] = node.node_id

        for item in payload.get("tasks", ()):
            task_id = self._stable_id("plan-task", draft.draft_id, item["id"])
            node = graph.register_existing_subject(
                node_id=f"node:task:{task_id}",
                project_id=project_id,
                node_type=WorkNodeType.TASK,
                subject_id=task_id,
            )
            local_nodes[item["id"]] = node.node_id

        semantic_edges: list[tuple[str, str, str]] = []
        for item in payload.get("requirements", ()):
            semantic_edges.append((item["id"], "derived_from", item["goal_id"]))
        for item in payload.get("phases", ()):
            if item.get("milestone_id"):
                semantic_edges.append((item["id"], "part_of", item["milestone_id"]))
        for item in payload.get("tasks", ()):
            if item.get("phase_id"):
                semantic_edges.append((item["id"], "part_of", item["phase_id"]))
        for item in payload.get("risks", ()):
            semantic_edges.append((item["id"], "relates_to", goal["id"]))
        for item in payload.get("dependencies", ()):
            semantic_edges.append((item["source_id"], item["relation_type"], item["target_id"]))
        for source, relation_type, target in semantic_edges:
            graph.add_relation(
                relation_id=self._stable_id(
                    "relation", draft.draft_id, f"{source}|{relation_type}|{target}"
                ),
                project_id=project_id,
                source_node_id=local_nodes[source],
                relation_type=relation_type,
                target_node_id=local_nodes[target],
                created_by_type="plan",
                created_by_id=actor_id,
                source_run_id=draft.source_run_id,
            )

    def _materialize_v1_work_graph(self, *, project_id, draft, actor_id) -> None:
        graph = self.work_graph
        _, goal_node = graph.create_goal(
            goal_id=self._stable_id("goal", draft.draft_id, "goal"),
            project_id=project_id,
            title=draft.goals[:256],
            description=draft.scope,
            success_criteria=draft.acceptance_criteria,
            created_by=actor_id,
        )
        milestone_nodes = {}
        for index, item in enumerate(draft.milestones):
            local = f"milestone-{index}"
            _, node = graph.create_milestone(
                milestone_id=self._stable_id("milestone", draft.draft_id, local),
                project_id=project_id,
                title=str(item.get("name") or "未命名里程碑"),
                description=str(item.get("description") or item.get("name") or ""),
                target_at=self._optional_datetime(item.get("target")),
                completion_policy={"source_schema": "v1"},
            )
            milestone_nodes[index] = node
            graph.add_relation(
                relation_id=self._stable_id("relation", draft.draft_id, f"{local}|part_of|goal"),
                project_id=project_id,
                source_node_id=node.node_id,
                relation_type="part_of",
                target_node_id=goal_node.node_id,
                created_by_type="plan",
                created_by_id=actor_id,
                source_run_id=draft.source_run_id,
            )
        teams_by_kind = self._project_teams_by_kind(project_id)
        owner_team = self._project_owner_team(project_id)
        for index, item in enumerate(draft.phases):
            local = f"phase-{index}"
            owner = teams_by_kind.get(str(item.get("team_category") or ""))
            _, phase_node = graph.create_phase(
                phase_id=self._stable_id("phase", draft.draft_id, local),
                project_id=project_id,
                title=str(item.get("name") or f"Phase {index + 1}"),
                description=str(item.get("description") or item.get("name") or ""),
                milestone_id=None,
                owner_team_id=owner,
            )
            if owner and owner != owner_team:
                task_id = f"plan-ph-{draft.draft_id}-{index}"
                task_node = graph.register_existing_subject(
                    node_id=f"node:task:{task_id}",
                    project_id=project_id,
                    node_type="task",
                    subject_id=task_id,
                )
                graph.add_relation(
                    relation_id=self._stable_id(
                        "relation", draft.draft_id, f"task-{index}|part_of|{local}"
                    ),
                    project_id=project_id,
                    source_node_id=task_node.node_id,
                    relation_type="part_of",
                    target_node_id=phase_node.node_id,
                    created_by_type="plan",
                    created_by_id=actor_id,
                    source_run_id=draft.source_run_id,
                )
        for index, item in enumerate(draft.risks):
            _, node = graph.create_risk(
                risk_id=self._stable_id("risk", draft.draft_id, f"risk-{index}"),
                project_id=project_id,
                title=str(item.get("name") or item.get("title") or f"Risk {index + 1}"),
                description=str(item.get("description") or item.get("name") or "Risk"),
                severity=str(item.get("level") or "medium"),
                likelihood=str(item.get("likelihood") or "medium"),
                mitigation=str(item.get("mitigation") or "unspecified"),
                source_run_id=draft.source_run_id,
            )
            graph.add_relation(
                relation_id=self._stable_id(
                    "relation", draft.draft_id, f"risk-{index}|relates_to|goal"
                ),
                project_id=project_id,
                source_node_id=node.node_id,
                relation_type="relates_to",
                target_node_id=goal_node.node_id,
                created_by_type="plan",
                created_by_id=actor_id,
                source_run_id=draft.source_run_id,
            )

    @staticmethod
    def _stable_id(prefix: str, draft_id: str, local_id: str) -> str:
        digest = hashlib.sha256(f"{draft_id}\0{local_id}".encode("utf-8")).hexdigest()[:32]
        return f"{prefix}-{digest}"

    @staticmethod
    def _optional_datetime(value):
        if value in (None, ""):
            return None
        if isinstance(value, datetime):
            return value if value.tzinfo else value.replace(tzinfo=UTC)
        try:
            parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return None
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)

    def _project_teams_by_kind(self, project_id: str) -> dict:
        from .repository import PROJECT_TEAMS as TEAMS_TABLE

        with self.engine.connect() as connection:
            rows = (
                connection.execute(
                    select(TEAMS_TABLE.c.team_id, TEAMS_TABLE.c.kind).where(
                        TEAMS_TABLE.c.project_id == project_id
                    )
                )
                .mappings()
                .all()
            )
        return {row["kind"]: row["team_id"] for row in rows}

    def _project_owner_team(self, project_id: str) -> str | None:
        with self.engine.connect() as connection:
            return connection.execute(
                select(PROJECTS.c.owner_team_id).where(PROJECTS.c.project_id == project_id)
            ).scalar_one_or_none()

    def _plan_row_with_engine(self, *, draft_id: str) -> ProjectPlanDraft:
        with self.engine.connect() as connection:
            return self._plan_row(connection, draft_id=draft_id)

    def _find_draft_by_run(self, source_run_id: str) -> str | None:
        with self.engine.connect() as connection:
            return connection.execute(
                select(PROJECT_PLAN_DRAFTS.c.draft_id).where(
                    PROJECT_PLAN_DRAFTS.c.source_run_id == source_run_id
                )
            ).scalar_one_or_none()

    @staticmethod
    def _plan_row(connection, *, draft_id: str):
        row = (
            connection.execute(
                select(PROJECT_PLAN_DRAFTS).where(PROJECT_PLAN_DRAFTS.c.draft_id == draft_id)
            )
            .mappings()
            .one_or_none()
        )
        if row is None:
            raise ResourceNotFound("plan draft is unavailable")
        return ProjectPlanningService._plan(row)

    @staticmethod
    def _plan(row) -> ProjectPlanDraft:
        return ProjectPlanDraft(
            row["draft_id"],
            row["project_id"],
            row["source_conversation_id"],
            row["source_turn_id"],
            row["source_run_id"],
            row["schema_version"],
            dict(row["plan_payload"]),
            row["goals"],
            row["scope"],
            tuple(json.loads(row["phases"])),
            tuple(json.loads(row["milestones"])),
            tuple(json.loads(row["risks"])),
            tuple(json.loads(row["dependencies"])),
            tuple(json.loads(row["acceptance_criteria"])),
            row["content_sha256"],
            PlanDraftStatus(row["status"]),
            int(row["version"]),
            row["created_by"],
            ProductAccountService._aware(row["created_at"]),
            ProductAccountService._aware(row["updated_at"]),
            ProductAccountService._aware(row["approved_at"]) if row["approved_at"] else None,
            row["rejection_reason"],
        )

    @staticmethod
    def _requirement(row) -> ProjectTeamRequirementDraft:
        return ProjectTeamRequirementDraft(
            row["requirement_id"],
            row["project_id"],
            row["plan_draft_id"],
            row["team_category"],
            int(row["team_count"]),
            row["rationale"],
            PlanDraftStatus(row["status"]),
            row["created_by"],
            ProductAccountService._aware(row["created_at"]),
            ProductAccountService._aware(row["approved_at"]) if row["approved_at"] else None,
        )

    @staticmethod
    def _object_list(value, name):
        if not isinstance(value, list):
            raise ValueError(f"{name} must be a list")
        result = []
        for index, entry in enumerate(value):
            if not isinstance(entry, dict):
                raise ValueError(f"{name}[{index}] is malformed")
            result.append(entry)
        return result

    @staticmethod
    def _string_list(value, name):
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise ValueError(f"{name} must be a list of strings")
        return [item.strip() for item in value if item.strip()]

    def _require_participant(self, *, project_id: str, actor_id: str) -> None:
        with self.engine.connect() as connection:
            actor = ProductAccountService._account_row(connection, actor_id)
            visible = connection.execute(
                select(PROJECT_TEAMS.c.team_id).where(
                    and_(
                        PROJECT_TEAMS.c.project_id == project_id,
                        PROJECT_TEAMS.c.team_id == actor["team_id"],
                    )
                )
            ).scalar_one_or_none()
        if visible is None:
            raise ResourceNotFound("project is unavailable")
